# Generated by Django 2.2.5 on 2020-03-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='time_of_sale',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
