# Generated by Django 2.2.5 on 2020-03-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_sales_how_many'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
